apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlapp-deployment
  labels:
    app: htmlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmlapp
  template:
    metadata:
      labels:
        app: htmlapp 
    spec:
      containers:
      - name: htmlserver
        image: tahs01/todoapp-html:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: htmlapp-service
spec:
  selector:
    app: htmlapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31110
